apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-deployment
  labels:
    app: kafka-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui-deployment
  template:
    metadata:
      labels:
        app: kafka-ui-deployment
    spec:
      containers:
        - name: kafka-ui-deployment
          image: provectuslabs/kafka-ui:v0.7.2
          envFrom:
            - configMapRef:
                name: kafka-ui-config
          env:
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
