apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-service
  labels:
    app: kafka-broker-service
spec:
  clusterIP: None
  selector:
    app: kafka-broker-deployment
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
    - name: external
      port: 9094
      targetPort: 9094
 
